name: Build Kernel

on:
  workflow_dispatch:
jobs:
  create_tar:
    name: Create kernel tar
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout kernel 6.6
        uses: actions/checkout@v4
        with:
          repository: anon503/linux
          ref: refs/heads/linux-6.6
          path: linux-6.6.84
      - name: Pack kernel
        run: |
             tar -c linux-6.6.84 | xz -T0 > linux-6.6.84.tar.xz
             sha256sum linux-6.6.84.tar.xz > sha256sum-linux-6.6.84

      - name: Release build artifacts
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          prerelease: false
          name: kernel v6.6
          tag: v6.6
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
                    *.xz
                    sha256sum
